name: Offlinetech Template

on:
  push: 
    branches: [ $default-branch ]
  pull-request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Offlinetech
        